### ISSUE TITLE
set webhook

### ISSUE THREAD

**Issue by devRayanwv** [adilkhash/planetpython_telegrambot#1]
Hello,
Thank you for the tutorial, I really learnt a lot. I followed the steps and everything work as expected. Now I need to setup the webhook. I tried to play around with the code, but I couldn't. I am new with python web development. So, if there is any quick hint, I really appreciated. 

Thank you again

**Comment by adilkhash** [comment]
Hi Rayan!
Thanks for your kind feedback. In order to use webHook functionality, you have to explore Telegram's API setWebhook method - https://core.telegram.org/bots/api#setwebhook
I am going to write the second part of my post where I will show how to deploy and set up your bot as soon as possible (probably within 1-2 weeks).

**Comment by adilkhash** [comment]
I have translated a second part of my tutorial — https://khashtamov.com/en/how-to-deploy-telegram-bot-django/
